spring.application.name=racing-service

spring.datasource.url=jdbc:postgresql://localhost:5432/race_db
spring.datasource.username=race
spring.datasource.password=race
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#logging.level.root=debug

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema-generated.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
