spring.application.name=racing-service

spring.datasource.url=jdbc:postgresql://localhost:5432/race_db
spring.datasource.username=race
spring.datasource.password=race
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

engine.service-url=https://click-racer-983614458473.europe-north1.run.app/api/fragile-fast/points/earn
engine.service-fallback-url=https://click-racer-983614458473.europe-north1.run.app/api/stable-slow/points/earn

#logging.level.root=debug

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema-generated.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
