server:
  port: 8081

spring:
  application:
    name: sidewalk-donkey
  datasource:
    password: race
    driver-class-name: org.postgresql.Driver
    username: race
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/race_db
  threads:
    virtual:
      enabled: true

job:
  race-consistency:
    repeat-millis: 5

#logging:
#  root: debug