spring:
  application:
    name: racing-service
  datasource:
    password: race
    driver-class-name: org.postgresql.Driver
    username: race
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/race_db

    hikari:
      minimumIdle: 2
      maximumPoolSize: 1000
      idleTimeout: 30_000
      connectionTimeout: 30_000
      leakDetectionThreshold: 60_000

  jpa:
    hibernate:
      ddl-auto: validate
  #    show-sql: 'true'
  threads:
    virtual:
      enabled: true

engine:
  service-url: https://click-racer-983614458473.europe-north1.run.app/api/fragile-fast/points/earn
  service-fallback-url: https://click-racer-983614458473.europe-north1.run.app/api/stable-slow/points/earn

application:
  sidewalk:
    donkey-enabled: true

#management:
#  endpoint:
#    metrics:
#      enabled=true
#logging:
#  root: debug